using System.IO.Abstractions;
using System.IO.Abstractions.TestingHelpers;
using Legislator.Core.Options;
using Legislator.Engine.Jobs;
using Legislator.TestSupport;
using Xunit;

namespace Legislator.Engine.Tests.Jobs;

/// <summary>
/// The baseline job, branch by branch — the R-NNN to annotated-test register, and the engine's
/// only write. What the twins assert about its properties, these assert about its bytes: the
/// document is a generated artifact whose exact shape is its contract with the reader.
/// </summary>
public sealed class BaselineJobTests
{
    /// <summary>
    /// The traceability marker, assembled rather than written: `core/artifact-lifecycle.md`
    /// annotates a test by the literal `per R-NNN` it carries, and a fixture that spelled the
    /// marker whole would enter the baseline as an annotation for requirements it does not
    /// test - a false green in the register a human reads.
    /// </summary>
    private const string Per = "per ";

    private const string Target = "/r/docs/ai/baseline.md";

    private static MockFileSystem Repo(Dictionary<string, string> files)
    {
        var fs = new MockFileSystem();
        fs.AddDirectory("/r/docs/okf");
        foreach (var (rel, text) in files)
        {
            fs.AddFile($"/r/{rel}", new MockFileData(text));
        }

        return fs;
    }

    private static JobResult Run(IFileSystem fs, LegislatorOptions? options = null) =>
        new BaselineJob().Run(new JobContext(
            fs, TimeProvider.System, new FakeEnvironment(), new FakeProcessRunner(),
            options ?? new LegislatorOptions(), "/r", []));

    private const string Header =
        "<!-- GENERATED by `legislator baseline` — do not edit.\n"
        + "     Sources: EARS headings in docs/cases/*/spec.md; the literal\n"
        + "     marker `per R-NNN` in test source files. Regenerate on demand;\n"
        + "     this file dies with its sources (core/artifact-lifecycle.md,\n"
        + "     generated class). -->\n"
        + "\n"
        + "# Baseline — what the system must do today\n"
        + "\n"
        + "| Requirement | Definition | Case | Annotated tests |\n"
        + "|---|---|---|---|\n";

    [Fact]
    public void The_document_is_the_header_the_rows_and_the_uncovered_list()
    {
        var fs = Repo(new()
        {
            ["docs/cases/BL-001-x/spec.md"] = "# BL-001\n\n### R-001 — widgets persist\n\na SHALL b.\n\n### R-002 — widgets list\n\nc SHALL d.\n",
            ["src/App.Tests/WidgetStoreTests.cs"] = "// " + Per + "R-001\n",
        });

        var result = Run(fs);

        Assert.Equal(0, result.ExitCode);
        Assert.Equal("", result.Stdout);
        Assert.Equal(
            Header
            + "| R-001 | widgets persist | `docs/cases/BL-001-x` | `src/App.Tests/WidgetStoreTests.cs` |\n"
            + "| R-002 | widgets list | `docs/cases/BL-001-x` | — |\n"
            + "\n## Uncovered — requirements no test carries\n\n"
            + "- R-002 — widgets list (`docs/cases/BL-001-x`)\n",
            fs.File.ReadAllText(Target));
    }

    [Fact]
    public void A_repository_whose_requirements_are_all_covered_says_none()
    {
        var fs = Repo(new()
        {
            ["docs/cases/BL-001-x/spec.md"] = "# BL-001\n\n### R-001 — widgets persist\n\na SHALL b.\n",
            ["src/App.Tests/WidgetStoreTests.cs"] = "// " + Per + "R-001\n",
        });

        Run(fs);

        Assert.EndsWith("\n## Uncovered — requirements no test carries\n\n(none)\n", fs.File.ReadAllText(Target), StringComparison.Ordinal);
    }

    /// <summary>A pipe inside a definition would break the table it is printed into.</summary>
    [Fact]
    public void A_pipe_in_a_definition_is_escaped()
    {
        var fs = Repo(new() { ["docs/cases/BL-001-x/spec.md"] = "# BL-001\n\n### R-001 — a | b\n\nx SHALL y.\n" });

        Run(fs);

        Assert.Contains(@"| R-001 | a \| b |", fs.File.ReadAllText(Target), StringComparison.Ordinal);
    }

    /// <summary>A marker names an id without a case, so a colliding id maps the test into every case that defines it — the ambiguity is displayed, not resolved silently.</summary>
    [Fact]
    public void An_id_defined_in_two_cases_gets_a_row_each()
    {
        var fs = Repo(new()
        {
            ["docs/cases/BL-001-a/spec.md"] = "# a\n\n### R-001 — first\n\nx SHALL y.\n",
            ["docs/cases/BL-002-b/spec.md"] = "# b\n\n### R-001 — second\n\nx SHALL z.\n",
            ["src/App.Tests/T.cs"] = "// " + Per + "R-001\n",
        });

        Run(fs);

        var text = fs.File.ReadAllText(Target);
        Assert.Contains("| R-001 | first | `docs/cases/BL-001-a` | `src/App.Tests/T.cs` |", text, StringComparison.Ordinal);
        Assert.Contains("| R-001 | second | `docs/cases/BL-002-b` | `src/App.Tests/T.cs` |", text, StringComparison.Ordinal);
    }

    [Fact]
    public void Annotated_tests_are_listed_sorted_and_only_from_files_whose_path_says_test()
    {
        var fs = Repo(new()
        {
            ["docs/cases/BL-001-x/spec.md"] = "# BL-001\n\n### R-001 — a\n\nx SHALL y.\n",
            ["src/b.Tests/B.cs"] = "// " + Per + "R-001\n",
            ["src/a.Tests/A.cs"] = "// " + Per + "R-001\n",
            ["src/App/Production.cs"] = "// " + Per + "R-001\n",
        });

        Run(fs);

        Assert.Contains("| R-001 | a | `docs/cases/BL-001-x` | `src/a.Tests/A.cs`, `src/b.Tests/B.cs` |",
            fs.File.ReadAllText(Target), StringComparison.Ordinal);
    }

    /// <summary>Build output is not source at any depth, and `docs/` is not a source root.</summary>
    [Fact]
    public void Build_output_and_the_docs_tree_carry_no_markers()
    {
        var fs = Repo(new()
        {
            ["docs/cases/BL-001-x/spec.md"] = "# BL-001\n\n### R-001 — a\n\nx SHALL y.\n",
            ["src/App/obj/Debug/Tests.g.cs"] = "// " + Per + "R-001\n",
            ["docs/cases/BL-001-x/test-notes.md"] = "" + Per + "R-001\n",
        });

        Run(fs);

        Assert.Contains("| R-001 | a | `docs/cases/BL-001-x` | — |", fs.File.ReadAllText(Target), StringComparison.Ordinal);
    }

    [Fact]
    public void The_target_comes_from_the_options_model()
    {
        var fs = Repo(new() { ["docs/cases/BL-001-x/spec.md"] = "# BL-001\n\n### R-001 — a\n\nx SHALL y.\n" });

        Run(fs, new LegislatorOptions { BaselineFile = new("register.md", OptionsLayer.Instance) });

        Assert.True(fs.File.Exists("/r/docs/ai/register.md"));
        Assert.False(fs.File.Exists(Target));
    }

    [Fact]
    public void A_repository_with_no_cases_still_writes_the_document()
    {
        var fs = Repo(new() { ["README.md"] = "# hi\n" });

        var result = Run(fs);

        Assert.Equal(0, result.ExitCode);
        Assert.EndsWith("(none)\n", fs.File.ReadAllText(Target), StringComparison.Ordinal);
    }

    [Fact]
    public void The_job_is_named_baseline() => Assert.Equal("baseline", new BaselineJob().Name);
}
