<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>legislator</AssemblyName>
    <PublishAot>true</PublishAot>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Legislator.Engine/Legislator.Engine.csproj" />
    <ProjectReference Include="../Legislator.Hooks/Legislator.Hooks.csproj" />
    <PackageReference Include="TestableIO.System.IO.Abstractions.Wrappers" />
  </ItemGroup>
</Project>
