using System.IO.Abstractions;
using Legislator.Core.Repo;
using Legislator.Engine.Anchors;
using Legislator.Engine.Sdd;

namespace Legislator.Engine.Jobs;

/// <summary>
/// Writes the baseline - the ONE write this engine performs (ADR-0003) - and reports nothing.
/// The document is the generated class's first member: same repository state, same bytes, so
/// regeneration over an unchanged tree is a zero diff and a hand edit never survives a run. It
/// is staged beside its target and moved into place, so a crash leaves the target untouched or
/// fully rewritten; exit 3 can never mean a half-written artifact.
/// </summary>
public sealed class BaselineJob : IJob
{
    public string Name => "baseline";

    public string Usage => Name;

    public JobResult Run(JobContext ctx)
    {
        ArgumentNullException.ThrowIfNull(ctx);

        var fs = ctx.Fs;
        var layout = new RepoLayout(ctx.Options, ctx.Root);

        // Keyed by case and id together: R-NNN is unique within a case only. A test marker
        // names an id without a case, so a colliding id maps the test into every case that
        // defines it - the ambiguity is displayed, not resolved silently.
        var rows = new SortedDictionary<(string Case, string Id), string>(Comparer<(string Case, string Id)>.Create(
            (left, right) => StringComparer.Ordinal.Compare(left.Case, right.Case) is var byCase && byCase != 0
                ? byCase
                : StringComparer.Ordinal.Compare(left.Id, right.Id)));

        foreach (var file in CaseModel.Load(fs, layout))
        {
            foreach (var (id, definition) in file.Requirements)
            {
                rows[(file.Relative, id)] = definition.Replace("|", @"\|", StringComparison.Ordinal);
            }
        }

        var covered = AnnotatedTests(fs, ctx);
        var lines = new List<string>
        {
            $"<!-- GENERATED by `{ctx.Options.ArmExecutable.Value} baseline` — do not edit.",
            "     Sources: EARS headings in docs/cases/*/spec.md; the literal",
            "     marker `per R-NNN` in test source files. Regenerate on demand;",
            "     this file dies with its sources (core/artifact-lifecycle.md,",
            "     generated class). -->",
            "",
            "# Baseline — what the system must do today",
            "",
            "| Requirement | Definition | Case | Annotated tests |",
            "|---|---|---|---|",
        };

        foreach (var ((caseRelative, id), definition) in rows)
        {
            var tests = covered.TryGetValue(id, out var files) && files.Count > 0
                ? string.Join(", ", files.Select(f => $"`{f}`"))
                : "—";
            lines.Add($"| {id} | {definition} | `{caseRelative}` | {tests} |");
        }

        lines.AddRange(["", "## Uncovered — requirements no test carries", ""]);
        var uncovered = rows.Where(row => !covered.ContainsKey(row.Key.Id)).ToList();
        lines.AddRange(uncovered.Count > 0
            ? uncovered.Select(row => $"- {row.Key.Id} — {row.Value} (`{row.Key.Case}`)")
            : ["(none)"]);

        Write(fs, layout.Baseline, string.Join('\n', lines) + "\n");
        return new JobResult(0, "", "");
    }

    /// <summary>Requirement id to the sorted test files carrying its `per R-NNN` marker - a test is annotated by the literal marker, nothing else.</summary>
    private static Dictionary<string, List<string>> AnnotatedTests(IFileSystem fs, JobContext ctx)
    {
        var covered = new Dictionary<string, List<string>>(StringComparer.Ordinal);
        foreach (var relative in SourceTree.Files(fs, ctx.Root, ctx.Options))
        {
            if (!relative.Contains("test", StringComparison.OrdinalIgnoreCase))
            {
                continue;
            }

            string text;
            try
            {
                text = fs.File.ReadAllText($"{ctx.Root}/{relative}");
            }
            catch (IOException)
            {
                continue;
            }
            catch (UnauthorizedAccessException)
            {
                continue;
            }

            foreach (var id in Prose.PerRefs(text))
            {
                if (!covered.TryGetValue(id, out var files))
                {
                    covered[id] = files = [];
                }

                files.Add(relative);
            }
        }

        foreach (var files in covered.Values)
        {
            files.Sort(StringComparer.Ordinal);
        }

        return covered;
    }

    /// <summary>Staged beside the target and moved over it: the target is the old document or the new one, never half of either.</summary>
    private static void Write(IFileSystem fs, string target, string content)
    {
        var directory = target[..target.LastIndexOf('/')];
        fs.Directory.CreateDirectory(directory);
        var staged = $"{directory}/.baseline-{Guid.NewGuid():N}.tmp";
        try
        {
            fs.File.WriteAllText(staged, content);
            fs.File.Move(staged, target, overwrite: true);
        }
        catch
        {
            if (fs.File.Exists(staged))
            {
                fs.File.Delete(staged);
            }

            throw;
        }
    }
}
