<Project>
  <ItemGroup>
    <PackageVersion Include="TestableIO.System.IO.Abstractions" Version="22.2.0" />
    <PackageVersion Include="TestableIO.System.IO.Abstractions.Wrappers" Version="22.2.0" />
    <PackageVersion Include="TestableIO.System.IO.Abstractions.TestingHelpers" Version="22.2.0" />
    <PackageVersion Include="YamlDotNet" Version="18.1.0" />
    <PackageVersion Include="xunit.v3" Version="4.0.0" />
    <PackageVersion Include="Microsoft.Testing.Extensions.CodeCoverage" Version="18.10.0" />
  </ItemGroup>
</Project>
